#!/system/bin/sh
# version 1.3

#Create logfile
if [ ! -e /data/local/tmp/gcconf.log ] ;then
    touch /data/local/tmp/gcconf.log
fi

echo "`date +%Y-%m-%d_%T` Starting crond" >> /data/local/tmp/gcconf.log
crond -b -c /data/crontabs
